### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by AndyOGo** [adobe/jsonschema2md#198]
## What did you do

Running as NPM script:
`jsonschema2md -o docs/ -x docs/ -d schemas/ -e json`

## What did you expect to happen

No warnings of unhandled promise rejections.

## What happened

**Note:** I reference unloaded JSON schemas of another project.

```sh
(node:23354) UnhandledPromiseRejectionWarning: TypeError: Cannot convert object to primitive value
    at makeconstraintssection (/Users/axawinterthur/dev/aletheia/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:590:33)
    at Object.entries.map (/Users/axawinterthur/dev/aletheia/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:715:14)
    at Array.map (<anonymous>)
    at makeproplist (/Users/axawinterthur/dev/aletheia/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:705:54)
    at makeproperties (/Users/axawinterthur/dev/aletheia/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:819:12)
    at foldl (/Users/axawinterthur/dev/aletheia/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:843:10)
    at each (/Users/axawinterthur/dev/aletheia/node_modules/ferrum/src/sequence.js:984:12)
    at curry (/Users/axawinterthur/dev/aletheia/node_modules/ferrum/src/sequence.js:582:5)
    at each [CURRY] (/Users/axawinterthur/dev/aletheia/node_modules/ferrum/src/functional.js:169:12)
    at curry (/Users/axawinterthur/dev/aletheia/node_modules/ferrum/src/sequence.js:983:3)
(node:23354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## What's your environment

* Operating System: macOS Catalina `10.15.2 (19C57)`
* node.js version: `v10.15.0`

## Do you have example files:

Sorry, not publicly available for this.

I have the full log only:

```sh
> jsonschema2md -o docs/ -x docs/ -d schemas/ -e json

loading 53 schemas
cannot resolve http://jsonlogic.com/schemas/json-logic.json
cannot resolve http://jsonlogic.com/schemas/json-logic.json
writing schemas
writing schemas to .../docs
writing README
building readme
writing documentation
generating markdown
(node:23354) UnhandledPromiseRejectionWarning: TypeError: Cannot convert object to primitive value
    at makeconstraintssection (.../node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:590:33)
    at Object.entries.map (.../node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:715:14)
    at Array.map (<anonymous>)
    at makeproplist (.../node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:705:54)
    at makeproperties (.../node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:819:12)
    at foldl (.../node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:843:10)
    at each (.../node_modules/ferrum/src/sequence.js:984:12)
    at curry (.../node_modules/ferrum/src/sequence.js:582:5)
    at each [CURRY] (.../node_modules/ferrum/src/functional.js:169:12)
    at curry (.../node_modules/ferrum/src/sequence.js:983:3)
(node:23354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
.../docs/README.md created
```

**Comment by trieloff** [comment]
Do you have a schema where `format` is not a string?

**Comment by AndyOGo** [comment]
I have an object type listing a `format` property, like:
Do you mean it's colliding with[ type string `format` validator](https://json-schema.org/understanding-json-schema/reference/string.html#format)?

```js
{
      "type": "object",
      "title": "Properties",
      "description": "Properties of Datepicker.",

      "additionalProperties": false,
      "properties": {
        "format": {
          "type": "string",
          "title": "Format",
          "description": "Formatting used to display the date."
        },
        "value": {
          "type": "string",
          "title": "Value",
          "description": "Date to be displayed."
        }
      }
```

**Comment by trieloff** [comment]
Yes, that's exactly what's happening. I can fix this.

**Comment by AndyOGo** [comment]
@trieloff Thanks again for your quick help.

I have more output now, but another unhandled promise rejection.

```sh
(node:26127) UnhandledPromiseRejectionWarning: TypeError: Cannot convert object to primitive value
    at String (<anonymous>)
    at longestStreak (/Users/axawinterthur/dev/aletheia/node_modules/longest-streak/index.js:16:11)
    at Of.inlineCode (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/visitors/inline-code.js:30:39)
    at Of.one [as visit] (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/one.js:19:30)
    at Of.all (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/all.js:14:27)
    at Of.tableCell (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/visitors/table-cell.js:8:15)
    at Of.one [as visit] (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/one.js:19:30)
    at Of.all (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/all.js:14:27)
    at Of.table (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/visitors/table.js:44:26)
    at Of.one [as visit] (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/one.js:19:30)
(node:26127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
