### ISSUE TITLE
More type errors

### ISSUE THREAD

**Issue by trieloff** [adobe/jsonschema2md#201]
@trieloff Thanks again for your quick help.

I have more output now, though another unhandled promise rejection.
We use other keywords as keys too,  e.g. object type `properties` or array type `items` keywords, but those are all not primitives... 🤔 

```sh
(node:26127) UnhandledPromiseRejectionWarning: TypeError: Cannot convert object to primitive value
    at String (<anonymous>)
    at longestStreak (/Users/axawinterthur/dev/aletheia/node_modules/longest-streak/index.js:16:11)
    at Of.inlineCode (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/visitors/inline-code.js:30:39)
    at Of.one [as visit] (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/one.js:19:30)
    at Of.all (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/all.js:14:27)
    at Of.tableCell (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/visitors/table-cell.js:8:15)
    at Of.one [as visit] (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/one.js:19:30)
    at Of.all (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/all.js:14:27)
    at Of.table (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/visitors/table.js:44:26)
    at Of.one [as visit] (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/one.js:19:30)
(node:26127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

_Originally posted by @AndyOGo in https://github.com/adobe/jsonschema2md/issues/198#issuecomment-574144622_

**Comment by trieloff** [comment]
@AndyOGo this one looks different, as it seems to fail in the processing of an `inlineCode` block in Markdown. Maybe you can isolate the error and share an example schema.

**Comment by AndyOGo** [comment]
@trieloff Okay.
So I added a `try/catch` block at:
https://github.com/wooorm/longest-streak/blob/7abefd44375aa51e976e3939dbc7f7d965310ec8/index.js#L16

Which yields this log:

```sh
TypeError: Cannot convert object to primitive value
    at String (<anonymous>)
    at longestStreak (/Users/axawinterthur/dev/aletheia/node_modules/longest-streak/index.js:17:11)
    at Of.inlineCode (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/visitors/inline-code.js:30:39)
    at Of.one [as visit] (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/one.js:19:30)
    at Of.all (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/all.js:14:27)
    at Of.tableCell (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/visitors/table-cell.js:8:15)
    at Of.one [as visit] (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/one.js:19:30)
    at Of.all (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/all.js:14:27)
    at Of.table (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/visitors/table.js:44:26)
    at Of.one [as visit] (/Users/axawinterthur/dev/aletheia/node_modules/remark-stringify/lib/macro/one.js:19:30)
{ type: 'string',
  enum: [ 'button', 'submit', 'reset' ],
  title: 'Type',
  description: 'The type of the Button (not used for anchors).',
  [Symbol(myslug)]: 'button-properties-properties-properties-type' }
```
