### ISSUE TITLE
Error: Cannot find module 'es2015-i18n-tag'

### ISSUE THREAD

**Issue by AndyOGo** [adobe/jsonschema2md#207]
## What did you do

Upgrade to `4.0.9`.

## What did you expect to happen

Running without error

## What happened

**Error: Cannot find module 'es2015-i18n-tag'**
```sh
npm run test

> cyclic-schemas-test@1.0.0 test .../dev/cyclic-schemas-test
> jsonschema2md -o docs/ -x docs/ -d schemas/ -e json

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'es2015-i18n-tag'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (.../dev/cyclic-schemas-test/node_modules/@adobe/jsonschema2md/lib/index.js:23:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

## What's your environment

* Operating System: macOS Catalina `10.15.2 (19C57)`
* node.js version: `v10.15.0`

## Do you have example files:

PR: https://github.com/axa-ch/cyclic-schemas-test/pull/2/files#r368655818

**Comment by AndyOGo** [comment]
It doesn't seem to be installed properly 🤔 

```sh
ls -a ./node_modules/es2015-i18n-tag/
.			.all-contributorsrc	CONTRIBUTING.md		README.md		package.json
..			CHANGELOG.md		LICENSE			benchmark.js		yarn.lock
```

**Comment by AndyOGo** [comment]
@trieloff 
Alright, `es2015-i18n-tag` has been deprecated just a day ago it seems...

<img width="1062" alt="Screenshot 2020-01-20 at 23 39 03" src="https://user-images.githubusercontent.com/914443/72761989-2e130b80-3bde-11ea-88b2-d510d2d40bd3.png">

**Comment by AndyOGo** [comment]
https://github.com/skolmer/es2015-i18n-tag/issues/71

**Comment by skolmer** [comment]
Bad testing on my side, sorry for that ☹️ The build process should have failed because of missing artifacts in the output bundle. I will optimize the build script for the next release.

**Comment by trieloff** [comment]
Ok, we'll just pin the previous release.

**Comment by AndyOGo** [comment]
awesome, thanks a lot 👍

**Comment by trieloff** [comment]
If all fixes were that easy…

**Comment by AndyOGo** [comment]
It has been fixed in `es2015-i18n-tag` 🎉 
https://github.com/skolmer/es2015-i18n-tag/issues/71
