### ISSUE TITLE
npm test failing

### ISSUE THREAD

**Issue by trieloff** [adobe/jsonschema2md#240]
Running `npm test` fails:

```
  1) Testing Markdown Builder: title
       Meta Schema looks OK:

      AssertionError [ERR_ASSERTION]: '## Meta Type\n\nunknown ([Meta](meta.md))\n\n# Meta Definitions\n\n## Definitions group meta\n\nReference this group by usin... == 'defined in: [Meta](meta-definitions-meta-properties-title.md "https&#x3A;//ns.adobe.com/helix/pipeline/meta#/definitions/met...
      + expected - actual

      -## Meta Type
      -
      -unknown ([Meta](meta.md))
      -
      -# Meta Definitions
      -
      -## Definitions group meta
      -
      -Reference this group by using
      -
      -```json
      -{"$ref":"https://ns.adobe.com/helix/pipeline/meta#/definitions/meta"}
      -```
      -
      -
      -
      -
      -`meta`
      -
      --   is optional
      --   Type: `object` ([Details](meta-definitions-meta.md))
      --   can be null
      --   defined in: [Meta](meta-definitions-meta.md "https&#x3A;//ns.adobe.com/helix/pipeline/meta#/definitions/meta")
      -
      -### meta Type
      -
      -`object` ([Details](meta-definitions-meta.md))
      +defined in: [Meta](meta-definitions-meta-properties-title.md "https&#x3A;//ns.adobe.com/helix/pipeline/meta#/definitions/meta/properties/title")

      at Object.tester.fuzzy (test/testUtils.js:57:16)
      at Context.it (test/markdownBuilder.test.js:76:13)
```

and

```
  2) Testing Markdown Builder: readme-1
       Abstract Schema looks OK:

      AssertionError [ERR_ASSERTION]: Markdown output does not contain search string "nonfoo Access Restrictions"
# Abstract Schema

```txt
https://example.com/schemas/abstract
```

This is an abstract schema. It has `definitions`, but does not declare any properties

| [Abstract](fooabstract.html "What does Abstract mean?") | Extensible | Status         | Identifiable            | Custom Properties | Additional Properties | Access Restrictions       | Defined In                                                                                                     |
| :------------------------------------------------------ | ---------- | -------------- | ----------------------- | :---------------- | --------------------- | ------------------------- | -------------------------------------------------------------------------------------------------------------- |
| Can be instantiated                                     | No         | Unknown status | Unknown identifiability | Forbidden         | Allowed               | cannot be read or written | [abstract.schema.json](/code/jsonschema2md/test/fixtures/readme-1/abstract.schema.json "open original schema") |

## Abstract Type

`object` ([Abstract](abstract.md))

# Abstract Definitions

## Definitions group first

Reference this group by using

```json
{"$ref":"https://example.com/schemas/abstract#/$defs/first"}
```

`first`

-   is optional
-   Type: `object` ([Details](abstract-defs-first.md))
-   cannot be null
-   defined in: [Abstract](abstract-defs-first.md "https&#x3A;//example.com/schemas/abstract#/$defs/first")

### first Type

`object` ([Details](abstract-defs-first.md))

## Definitions group second

Reference this group by using

```json
{"$ref":"https://example.com/schemas/abstract#/$defs/second"}
```

`second`

-   is optional
-   Type: `object` ([Details](abstract-defs-second.md))
-   cannot be null
-   defined in: [Abstract](abstract-defs-second.md "https&#x3A;//example.com/schemas/abstract#/$defs/second")

### second Type

`object` ([Details](abstract-defs-second.md))

      + expected - actual

      -false
      +true

      at Object.tester.contains (test/testUtils.js:28:14)
      at Context.it (test/markdownBuilder.test.js:347:8)
```

**Comment by trieloff** [comment]
`git bisect` points at https://github.com/adobe/jsonschema2md/commit/2fb9fc5846b64df7cd54f39e3ef10f2da5cef75e
