### ISSUE TITLE
 TypeError: schema[keyword(...)].map(...) is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by felixleopoldo** [adobe/jsonschema2md#280]
### Expected Behaviour
I just wanted to generate a Markdown from my json schema.
### Actual Behaviour
It just reates the README.md but nothing else.
#### Steps to Reproduce
`jsonschema2md -d workflow/schemas/ -o workflow/schemas/docs/ -v 04
loading 2 schemas
writing schemas
writing schemas to /home/felix/git/benchpress/out
writing README
building readme
writing documentation
generating markdown
(node:5530) UnhandledPromiseRejectionWarning: TypeError: schema[keyword(...)].map(...) is not a function or its return value is not iterable
    at makeconstraintssection (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:564:34)
    at foldl (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:862:10)
    at each (/usr/local/lib/node_modules/@adobe/jsonschema2md/node_modules/ferrum/src/sequence.js:1014:12)
    at curry (/usr/local/lib/node_modules/@adobe/jsonschema2md/node_modules/ferrum/src/sequence.js:604:5)
    at each [CURRY] (/usr/local/lib/node_modules/@adobe/jsonschema2md/node_modules/ferrum/src/functional.js:175:12)
    at curry (/usr/local/lib/node_modules/@adobe/jsonschema2md/node_modules/ferrum/src/sequence.js:1013:3)
    at foldl [CURRY] (/usr/local/lib/node_modules/@adobe/jsonschema2md/node_modules/ferrum/src/functional.js:175:12)
    at /usr/local/lib/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:855:23
    at fns.reduce (/usr/local/lib/node_modules/@adobe/jsonschema2md/node_modules/ferrum/src/functional.js:88:53)
    at Array.reduce (<anonymous>)
(node:5530) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5530) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/home/felix/git/benchpress/workflow/schemas/docs/README.md created`
#### Platform and Version
5.0.1

**Comment by trieloff** [comment]
Are you able to share the schema that is failing?

**Comment by felixleopoldo** [comment]
Sure, here is a link https://pastebin.pl/view/89eebab8 .

Thanks in advance!

**Comment by felixleopoldo** [comment]
Hi, Did you try it out? I'm sorry to stress you, but your help would be very appreciated.

**Comment by trieloff** [comment]
Not yet. Creating a more minimal test case would help me in pinning down the problem.

**Comment by KatekovAnton** [comment]
I have similar issue trying to run the tool against my json schema:
```
❯ npx jsonschema2md -d $(pwd) -o $(pwd)
loading 1 schemas
(node:50784) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:122:11)
    at Object.parse (path.js:1283:5)
    at Object.get (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/schemaProxy.js:123:27)
    at Proxy.reduce (<anonymous>)
    at reducer (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:33:19)
    at Array.reduce (<anonymous>)
    at reducer (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:42:39)
    at Array.reduce (<anonymous>)
    at reducer (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:36:41)
    at Array.reduce (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:50784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:50784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is there any update on this? Thank you.

**Comment by felixleopoldo** [comment]
Hi,

It seemed like I had some problem with my schema, after I checked it with https://www.jsonschemavalidator.net/ it worked out. 
I thought I had done that before, but apparently not. Thanks for your willingness to help.

Felix
