### ISSUE TITLE
The "path" argument must be of type string

### ISSUE THREAD

**Issue by buremba** [adobe/jsonschema2md#295]
#### Platform and Version

MacOS, 6.0.0

#### Sample Code that illustrates the problem

jsonschema -d ./ ./docs

The directory includes a file called `dbt.schema.json`, the contents of the file is [here](https://app.rakam.io/schema/dbt.schema.json).

#### Logs taken while reproducing problem

```
loading 1 schemas
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
cannot resolve https://app.rakam.io/schema/model.schema.json
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Object.parse (node:path:1327:5)
    at Object.get (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/schemaProxy.js:123:27)
    at Function.values (<anonymous>)
    at reducer (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:36:25)
    at Array.reduce (<anonymous>)
    at reducer (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:42:39)
    at Array.reduce (<anonymous>)
    at reducer (/usr/local/lib/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:42:39) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by trieloff** [comment]
Is there a file with the schema ID `https://app.rakam.io/schema/model.schema.json` in the directory, too? `jsonschema2md` won't attempt to download the schema file via HTTP if it cannot be resolved locally.

**Comment by buremba** [comment]
Ah, that seems to be the issue. I denormalized the schema using `ref-parser`(https://github.com/APIDevTools/json-schema-ref-parser) it worked.
