### ISSUE TITLE
ERR_INVALID_ARG_TYPE: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by dominic-simplan** [adobe/jsonschema2md#392]
### Expected Behaviour
Converts JSON schema to MD.

### Actual Behaviour
The following error is thrown:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.parse (node:path:913:5)
    at Object.get (node_modules\@adobe\jsonschema2md\lib\schemaProxy.js:123:27)
    at Function.values (<anonymous>)
    at reducer (node_modules\@adobe\jsonschema2md\lib\traverseSchema.js:42:23)
    at Array.reduce (<anonymous>)
    at reducer (\node_modules\@adobe\jsonschema2md\lib\traverseSchema.js:36:41)
    at Array.reduce (<anonymous>)
    at reducer (node_modules\@adobe\jsonschema2md\lib\traverseSchema.js:42:39) {
  code: 'ERR_INVALID_ARG_TYPE'
```

#### Steps to Reproduce
Running with `jsonschema2md -d input -o output`
JSON Schema:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "ItemLink": {
            "properties": {
                "allowedSuccessors": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "class": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ItemLinkOptions": {
            "properties": {
                "allowedLinks": {
                    "items": {
                        "$ref": "#/definitions/ItemLink"
                    },
                    "type": "array"
                },
                "maxIncoming": {
                    "type": "number"
                },
                "maxOutgoing": {
                    "type": "number"
                }
            },
            "type": "object"
        }
    },
    "properties": {
        "id": {
            "type": "string"
        },
        "items": {
            "items": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/ItemLink"
                    }
                ]
            },
            "type": "array"
        },

        "version": {
            "type": "string"
        }
    },
    "type": "object"
}
```

#### Platform and Version
Windows 10

**Comment by stevecox** [comment]
Having the same problem on OSX.

**Comment by CarlosBergillos** [comment]
As a temporal solution you can use an explicit local URI in your `$ref`'s, pointing to the same file.

So, instead of:
```"$ref": "#/definitions/ItemLink"```

Try:
```"$ref": "./xxx.schema.json/#/definitions/ItemLink"```

This is not ideal, and having no explicit URI should work per spec, but I'm not familiar enough to know when it broke or how to fix it in a PR.

**Comment by trieloff** [comment]
Blocked by #395

**Comment by Finkman** [comment]
I have the same issue whenever I use a `$ref`.
(Running on Ubuntu)

**Comment by leverdeterre** [comment]
Same here, probably because the Schema director is expecting multiple schemas.
Maybe a workaround to develop is to be able to give in input just a single schema file instead of a schema directory ?

**Comment by gloaysa** [comment]
This can be solved by adding to your schema an $id with the path to itself from the root of the project.

**Comment by Finkman** [comment]
Seams to be an ugly workaround which does not lead to portable code

**Comment by huruji** [comment]
Having the same problem on OSX.

**Comment by grillba** [comment]
@trieloff  i see#395 is merged. Is it possible to progress a fix?

**Comment by zurmuehl** [comment]
@trieloff a fix would be highly appreciated.

**Comment by slhck** [comment]
Still getting this with v7.1.5, any updates?

**Comment by pkit** [comment]
Year passed, still totally unusable. Nice!

**Comment by deepakkumar18035** [comment]
> This can be solved by adding to your schema an $id with the path to itself from the root of the project.

As [gloaysa](https://github.com/gloaysa) mentioned, this can be solved by adding an `$id` to your schema; the value can be any string, not necessarily the path to itself.

**Comment by RuiRomano** [comment]
Same issue here

**Comment by vivdesign** [comment]
Any update  on this issue? I'm having the same problem and the "$id" workaround unfortunately is not an option

**Comment by Gpinchon** [comment]
Here we are one year later and this still seems like an issue, is this project still maintained ?

**Comment by trieloff** [comment]
I'm happy to review PRs, but there is little active development and maintenance is mostly limited to keeping dependencies up to date.
