### ISSUE TITLE
7.0.0 cli cannot be executed - throws Unexpected token error on import

### ISSUE THREAD

**Issue by BenjenJones** [adobe/jsonschema2md#407]
With the newest version 7.0.0 of jsonschema2md I cannot execute it anymore on commandline.
Version 6.1.4 works perfectly.

### Expected Behaviour

jsonschema2md on windows commandline should be executed normally

### Actual Behaviour

```bash
$ jsonschema2md.ps1 -d ./schema/ -o ./schema/docs/ -v 07
C:\Users\USERNAME\AppData\Roaming\npm\node_modules\@adobe\jsonschema2md\cli.js:14
import { main } from './lib/index.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
``` 

Executing the cli.js with node directly throws the same error. Same goes for the lib/index.js. lib/index.js will then throw error for the first import of yargs.

### Reproduce Scenario (including but not limited to)

```bash
$ npm install -g @adobe/jsonschema2md@6.1.4

# show usage information
$ jsonschema2md
```

and then execute

```bash
# run task
$ jsonschema2md -d ./schema/ -o ./schema/docs/ -v 07
```

#### Platform and Version

Windows 10
nodejs 12.3.1
npm 6.14.14

#### Logs taken while reproducing problem

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11

**Comment by trieloff** [comment]
This seems to be a node version issue. Could you try to update to a newer nodeJS version?

**Comment by BenjenJones** [comment]
but your package.json says

"engines": {
    "node": ">= 12.0.0"
}

did you test with a node version 12?

**Comment by trieloff** [comment]
Our CI is running on node 14, so no. I'm updating the minimum requirements.

**Comment by BenjenJones** [comment]
works with 14! Thanks
