### ISSUE TITLE
jsonschema2md syntaxerror after a fresh install and first run to show usage info

### ISSUE THREAD

**Issue by garfield69** [adobe/jsonschema2md#441]
### Expected Behaviour
show usage information
### Actual Behaviour
syntaxerror
### Reproduce Scenario (including but not limited to)
install jsonschema2md
run to show usage info
failure.
#### Steps to Reproduce
see log below
#### Platform and Version
windows 10
see npm and node versions in log below
#### Logs taken while reproducing problem
```
Garfield69@PC1 MINGW64 ~/Documents/GitHub/Jackett (master)
$ npm -v
8.12.1

Garfield69@PC1 MINGW64 ~/Documents/GitHub/Jackett (master)
$ node -v
v14.15.1

Garfield69@PC1 MINGW64 ~/Documents/GitHub/Jackett (master)
$ npm install -g @adobe/jsonschema2md

changed 118 packages, and audited 119 packages in 19s

64 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Garfield69@PC1 MINGW64 ~/Documents/GitHub/Jackett (master)
$ jsonschema2md
file:///C:/Users/Garfield69/AppData/Roaming/npm/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:13
import { list, eq, contains } from 'ferrum';
               ^^
SyntaxError: Named export 'eq' not found. The requested module 'ferrum' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'ferrum';
const { list, eq, contains } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

Garfield69@PC1 MINGW64 ~/Documents/GitHub/Jackett (master)
$
```

**Comment by trieloff** [comment]
Please try with node 16.

**Comment by garfield69** [comment]
Thank you, that did the trick.
Suggest you update https://github.com/adobe/jsonschema2md#requirements ;-)
