### ISSUE TITLE
Header Generation fails in XDM for aggregated-asset

### ISSUE THREAD

**Issue by trieloff** [adobe/jsonschema2md#66]
https://circleci.com/gh/adobe/xdm/2305

XDM is using version 1.0.5 and failing:

```
> shx mkdir -p docs/reference && jsonschema2md -o docs/reference -d schemas --link-abstract abstract.md --link-extensible extensions.md --link-status status.md --link-id --link-custom extensions.md --link-additional extensions.md

info: output directory: /home/circleci/repo/docs/reference
info: finished reading all *.schema.json files in /home/circleci/repo/schemas, beginning processing….
/home/circleci/repo/schemas/assets/aggregated-asset.schema.json
error:  TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1227:5)
    at link (/home/circleci/repo/node_modules/@adobe/jsonschema2md/lib/header.js:80:17)
    at headers (/home/circleci/repo/node_modules/@adobe/jsonschema2md/lib/header.js:105:50)
    at generateMarkdown (/home/circleci/repo/node_modules/@adobe/jsonschema2md/lib/markdownWriter.js:154:14)
    at Schema.getExamples.then.then.then.object (/home/circleci/repo/node_modules/@adobe/jsonschema2md/lib/schema.js:424:11)
```

**Comment by trieloff** [comment]
Closing: user error https://circleci.com/gh/adobe/xdm/2312
